/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlooidBuilderIndexRouteImport } from './routes/alooid-builder/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlooidBuilderIndexRoute = AlooidBuilderIndexRouteImport.update({
  id: '/alooid-builder/',
  path: '/alooid-builder/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alooid-builder/': typeof AlooidBuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alooid-builder': typeof AlooidBuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alooid-builder/': typeof AlooidBuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alooid-builder/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alooid-builder'
  id: '__root__' | '/' | '/alooid-builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlooidBuilderIndexRoute: typeof AlooidBuilderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alooid-builder/': {
      id: '/alooid-builder/'
      path: '/alooid-builder'
      fullPath: '/alooid-builder/'
      preLoaderRoute: typeof AlooidBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlooidBuilderIndexRoute: AlooidBuilderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
